stacks:
- content-api-sanity-tests
regions:
- eu-west-1
deployments:
  sanity-tests:
    type: autoscaling
    parameters:
      bucket: content-api-sanity-tests-dist
    dependencies: [sanity-tests-ami-update]
  sanity-tests-ami-update:
    type: ami-cloudformation-parameter
    app: sanity-tests
    parameters:
      amiTags:
        Recipe: ubuntu-xenial-java8
        AmigoStage: PROD
      amiEncrypted: true
